//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaDebugToolWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaDebugTool), typeof(System.Object));
		L.RegFunction("getUserDataInfo", getUserDataInfo);
		L.RegFunction("New", _CreateLuaDebugTool);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaDebugTool(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaDebugTool obj = new LuaDebugTool();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaDebugTool.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getUserDataInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			object arg0 = ToLua.ToVarObject(L, 1);
			System.Collections.Generic.List<LuaValueInfo> o = LuaDebugTool.getUserDataInfo(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

